version: 0.2

env:
  parameter-store:
    DOCKER_REGISTRY_USERNAME: /docker/username
    DOCKER_REGISTRY_PASSWORD: /docker/password
    DOCKER_REGISTRY_URL: /docker/registry-url

phases:
  install:
    runtime-versions:
      python: 3.11

  pre_build:
    commands:
      - echo "Logging into Docker"
      - echo "$DOCKER_REGISTRY_PASSWORD" | docker login -u "$DOCKER_REGISTRY_USERNAME" --password-stdin "$DOCKER_REGISTRY_URL"

  build:
    commands:
      - echo "Building Docker Image"
      - docker build -t "$DOCKER_REGISTRY_USERNAME/user-feedback-app:latest" .
      - docker tag "$DOCKER_REGISTRY_USERNAME/user-feedback-app:latest" "$DOCKER_REGISTRY_URL/$DOCKER_REGISTRY_USERNAME/user-feedback-app:latest"
      - docker push "$DOCKER_REGISTRY_URL/$DOCKER_REGISTRY_USERNAME/user-feedback-app:latest"

  post_build:
    commands:
      - echo "Build completed successfully"